### ISSUE TITLE
http://fantasy.codes/Base64/ not working

### ISSUE THREAD

**Issue by bean5** [SFantasy/Base64#1]
When I click 'Encode' or 'Decode', nothing happens.

**Comment by SFantasy** [comment]
@bean5 What's your input string ?

**Comment by bean5** [comment]
Encoding works now. I used `test` as my input. But when I decode the output from that (`dGVzdA==`), I get `undefined` and an alert popup.

It says `SyntaxError: Unexpected token e in JSON at position 1`.

I am using Chrome on a mac.

**Comment by bean5** [comment]
Now it is back to the original state where nothing is working. I'm sure you are close to getting it working!

**Comment by SFantasy** [comment]
@bean5 

Formerly, I assumed that the string to be decode is a encoded JSON string -- so when you input a string such as `test`, encode it, decode the encoded string would throw the error `SyntaxError: Unexpected token e in JSON at position 1`.

In this commit https://github.com/SFantasy/Base64/commit/dc01945905e9ac93d33662a2d2ee672d5aeb9da5#diff-55155a5dcc05bb7dd14ab82c5f8507baL15 the `decode` function would return the raw decoded string. So I don't know what's wrong with your browser...it works in mine.

**Comment by bean5** [comment]
Oh, I didn't realize this was for encoding/decoding of only JSON strings. Since that is the case, shouldn't the following throw an error (it is not valid JSON)?

`eyJ0ZXN0OnRydWV9`
